Repository 22nd-Hoondong/Re-Frame, pull requests merged in 2023-11, with the labels that each got.

#6 [chore/#2]: connect Firebase
  .gitignore
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: chore

#8 [chore/#7]: add firestore plugin
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: chore

#13 [feat/#12]: iOS/macOS 빌드 세팅 파일 수정
  .gitignore
  android/app/build.gradle
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Podfile
Labels: enhancement

#17 [feat/#15]: Firebase 구글 로그인
  assets/google.png
  lib/Pages/login.dart
  lib/main.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#18 [feat] 갤러리 화면
  android/build.gradle
  android/settings.gradle
  images/cork_board.jpg
  images/pin_transparent.png
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/Pages/gallery.dart
  lib/Widgets/image_container.dart
  lib/Widgets/photo_modal.dart
  lib/main.dart
  macos/Runner.xcodeproj/project.pbxproj
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#19 [Feat #16] 캘린더 화면 구현
  lib/Pages/calendar.dart
  lib/Widgets/photopage.dart
  lib/Widgets/postmodal.dart
  lib/calendar_util.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#21 [Feat/#11] 앱바 로직 페이지 내부로 옮기기
  lib/Pages/calendar.dart
  lib/Pages/gallery.dart
  lib/Pages/login.dart
  lib/main.dart
Labels: enhancement

#22 [FEAT] 페이지 뷰에 화면 전환 indicator추가
  lib/Widgets/photopage.dart
  lib/Widgets/postmodal.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#25 [Feat/#4] 친구 목록 화면
  lib/Bloc/friend_bloc.dart
  lib/Pages/friends.dart
  lib/Repository/friend_repository.dart
  lib/main.dart
Labels: enhancement

#29 Bug: floatingbutton이 올라오는 문제 수정
  lib/Pages/gallery.dart
  lib/Pages/upload.dart
  lib/main.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
Labels: bug

#30 [Feat/#23] 로그인/로그아웃
  android/app/src/main/AndroidManifest.xml
  assets/google.png
  images/sign_in_button.png
  lib/Pages/login.dart
  lib/Pages/setting.dart
  lib/main.dart
Labels: enhancement

#33 [BUG] 사용자 이름이 나오지 않는 문제 수정
  lib/Widgets/postmodal.dart
Labels: bug
